### ISSUE TITLE
tentando abrir com require("singularity-tagger") no observable da erro

### ISSUE THREAD

**Issue by dan-reznik** [loribeiro/Singularity-POS-Tagger#1]
o comando 

require("singularity-tagger") no observable da o seguinte erro:

Pe: invalid module

**Comment by loribeiro** [comment]
Olá @dan-reznik , desculpa pela demora!
Você poderia me dar mais informações sobre o contexto do erro? 
Fiz uma instalação limpa e funcionou sem apresentar problemas

Seria legal se você me dissesse qual a versão do Node.js está instalada no seu sistema
